language_machines/urls.py
from django.conf.urls import *  # NOQA
from django.conf.urls.i18n import i18n_patterns
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.conf import settings
from cms.sitemaps import CMSSitemap


admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/publications/publication/import_bibtex/$', 'publications.admin_views.import_bibtex'),
    url(r'^admin/', include(admin.site.urls)),  # NOQA
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': {'cmspages': CMSSitemap}}),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': 'static/'}),
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'},name='logout'),
    url(r'^', include('cms.urls')),
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',  # NOQA
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ) + staticfiles_urlpatterns() + urlpatterns  # NOQA

language_machines/lamadata/models.py
from django.db import models
from cms.models.fields import PlaceholderField
from publications.models import Publication
from django.conf import settings
from datetime import datetime
import random

PERSON_FUNCTIONS = { 'head':'Principal Investigator','phd':'PhD Candidate','postdoc':'Postdoc','prof':'Professor','assistantprof':'Assistant Professor','researcher':'Researcher','programmer':'Scientific Programmer','intern':'Intern','master':'Master\'s Candidate', 'bachelor':'Bachelor\'s Candidate', 'guest':'Guest Researcher','sysadmin':'System Administrator','assistant': 'Student Assistant' }
SOFTWARE_LICENSES = { 'gpl3': 'GNU Public License v3', 'gpl2': 'GNU Public License v2', 'agpl':'GNU Affero Public License v3','lgpl': 'Lesser GNU Public License v3', 'mit': 'MIT License', 'apache':'Apache License v2.0' }



class Person(models.Model):
    id = models.CharField("ID", help_text="ID, all lowercase and alphanumeric only, no spaces, will appear in URL like this", max_length=100, primary_key=True)
    firstname = models.CharField("First name", max_length=50)
    lastname = models.CharField("Last name", max_length=60)
    title = models.CharField("Title(s)", max_length=255, blank=True)
    nickname = models.CharField("Nickname", max_length=50, blank=True)
    affiliation = models.CharField("Affiliation", max_length=255,blank=True )
    function = models.CharField("Function", max_length=25,choices=sorted(PERSON_FUNCTIONS.items(), key= lambda x: x[1]))
    function2 = models.CharField("Secondary function", max_length=25,choices=sorted(PERSON_FUNCTIONS.items(), key=lambda x:x[1]), blank=True)
    interests = models.CharField("Interests", max_length=255,blank=True)
    email = models.CharField("E-mail", max_length=60)
    website = models.URLField("Website", max_length=60, blank=True)
    twitter = models.CharField("Twitter", max_length=60, blank=True)
    room = models.CharField("Room", max_length=60, blank=True)
    phone = models.CharField("Phone", max_length=60, blank=True)
    birth_date = models.DateField(blank=True,null=True)
    joined_date = models.DateField(blank=True,null=True)
    left_date = models.DateField(null=True,blank=True)
    description = models.TextField("Description",help_text="A short description about the person. For more text, use the content field.", blank=True)
    image = models.ImageField("Avatar",help_text="A 120x160 picture of the person, if not specified, you will be punished and a random llama will be shown.", upload_to='avatars/', blank=True, null=True)
    publications = models.ManyToManyField(Publication, blank=True)
    content = PlaceholderField('content')

    def __unicode__(self):
        return self.fullname()

    def getrandomlama(self):
        return settings.STATIC_URL +"/lama" + str(random.randint(1,6)) + ".jpg"

    def fullname(self):
        return self.firstname + " " + self.lastname

    def initialsname(self):
        return self.firstname[0] + ". " + self.lastname

    class Meta:
        ordering = ['joined_date', 'firstname', 'lastname']

class ProjectCategory(models.Model):
    id = models.CharField("ID", help_text="ID, all lowercase and alphanumeric only, no spaces, will appear in URL like this",max_length=100, primary_key=True)
    name = models.CharField("Category name", max_length=200)
    description = models.TextField("Description",help_text="A short description about the category.", blank=True)

    class Meta:
        verbose_name = "Project Category"
        verbose_name_plural = "Project Categories"
        ordering = ['name']


    def __unicode__(self):
        return self.name

class Software(models.Model):
    id = models.CharField("ID", help_text="ID, all lowercase and alphanumeric only, no spaces, will appear in URL like this",max_length=100, primary_key=True)
    name = models.CharField("Name", max_length=100)
    website = models.URLField("Website", help_text="Link to the software's dedicated website", blank=True,null=True)
    source = models.URLField("Source code", help_text="Link to source code repository or download", blank=True,null=True)
    webservice = models.URLField("Webservice", help_text="Link to Webservice URL", blank=True, null=True)
    demo = models.URLField("Demo", help_text="Link to the demo URL", blank=True,null=True)
    documentation = models.URLField("Documentation", help_text="Link to where the documentation is hosted",blank=True,null=True)
    license = models.CharField("License",max_length=10, choices=sorted(SOFTWARE_LICENSES.items(), key=lambda x: x[1]) )
    description = models.TextField("Description",help_text="A short description about the software. For more text, use the content field.", blank=True)
    authors = models.ManyToManyField(Person)
    externalauthors = models.CharField("External authors", max_length=255, help_text="Add any external authors (which are not in the system)",blank=True, null=True)
    publications = models.ManyToManyField(Publication, blank=True)
    image = models.ImageField("Software Logo", upload_to='softwarelogos/', blank=True, null=True)
    content = PlaceholderField('content')
    release_date = models.DateField(blank=True,null=True)
    category = models.ManyToManyField(ProjectCategory, blank=True)


    class Meta:
        verbose_name_plural = "Software"
        ordering = ['name']

    def __unicode__(self):
        return self.name



class Project(models.Model):
    id = models.CharField("ID", help_text="ID, all lowercase and alphanumeric only, no spaces, will appear in URL like this",max_length=100, primary_key=True)
    name = models.CharField("Project name", max_length=100)
    website = models.URLField("Website", help_text="Link to the project's dedicated website", blank=True,null=True)
    category = models.ManyToManyField(ProjectCategory, blank=True)
    start_date = models.DateField(blank=True)
    end_date = models.DateField(null=True,blank=True)
    sponsors = models.CharField("Sponsor(s)", max_length=255, blank=True)
    twitter = models.CharField("Twitter", max_length=60, blank=True)
    description = models.TextField("Description",help_text="A short description about the project. For more text, use the content field.", blank=True)
    members = models.ManyToManyField(Person, blank=True)
    externalmembers = models.CharField("External members", max_length=255, help_text="Add any external members (which are not in the system)",blank=True, null=True)
    software = models.ManyToManyField(Software, blank=True)
    publications = models.ManyToManyField(Publication, help_text="It is not necessary to explicitly add publications here, they will be automatically found!", blank=True)
    image = models.ImageField("Project logo", help_text="120x160px", upload_to='projectlogos/', blank=True, null=True)
    content = PlaceholderField('content')


    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['name']

language_machines/lamadata/views.py
# Create your views here.
from django.shortcuts import render_to_response
from django.template import RequestContext

from language_machines.lamadata.models import Person, Software, Project, ProjectCategory
from publications.models import Publication
from django.db.models import Q


def personindex(request):
    return render_to_response('personindex.html', {'persons': Person.objects.order_by('joined_date','firstname')}, context_instance=RequestContext(request) )

def projectindex(request):
    return render_to_response('projectindex.html', {'projects': Project.objects.order_by('name')}, context_instance=RequestContext(request) )

def home(request):
    return render_to_response('home.html', {'projectcategories': ProjectCategory.objects.order_by('name')}, context_instance=RequestContext(request) )

def softwareindex(request):
    return render_to_response('softwareindex.html', {'softwares': Software.objects.order_by('name')}, context_instance=RequestContext(request) )

def demoindex(request):
    return render_to_response('demoindex.html', {'softwares': Software.objects.order_by('name')}, context_instance=RequestContext(request) )

def personview(request, person_id):
    person = Person.objects.get(pk=person_id)
    softwares = Software.objects.filter(authors__id=person_id)
    projects = Project.objects.filter(members__id=person_id)
    publications = Publication.objects.filter(Q(authors__contains=person.initialsname()) | Q(authors__contains=person.fullname()) )
    return render_to_response('personview.html', {'person': person, 'softwares': softwares, 'projects': projects, 'publications': publications }, context_instance=RequestContext(request) )

def projectview(request, project_id):
    return render_to_response('projectview.html', {'project': Project.objects.get(pk=project_id)}, context_instance=RequestContext(request) )

def projectcategoryview(request, projectcategory_id):
    if projectcategory_id:
        projectcategory = ProjectCategory.objects.get(pk=projectcategory_id)
        projects = projectcategory.project_set.all()
        publications = Publication.objects.filter(project__category=projectcategory).distinct()
        softwares = Software.objects.filter(Q(project__category=projectcategory) | Q(category=projectcategory)).distinct()
        return render_to_response('projectcategoryview.html', {'projectcategory': projectcategory, 'projects': projects, 'publications': publications, 'softwares': softwares}, context_instance=RequestContext(request) )
    else:
        return home(request)

def softwareview(request, software_id):
    projects = Project.objects.filter(software__id=software_id)
    return render_to_response('softwareview.html', {'software': Software.objects.get(pk=software_id), 'projects': projects}, context_instance=RequestContext(request) )

def publicationindex(request, publication_id):
    pass

def publicationview(request, publication_id):
    pass

language_machines/templates/base.html
{% load cms_tags menu_tags sekizai_tags %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}Language Machines{% endblock title %}</title>
    {% render_block "css" %}

    {% load staticfiles %}

    <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />

</head>
<body>
<div id="gradient"></div>
{% cms_toolbar %}

    <div id="container">

      <div id="header">
         <div id="rulogo"></div>
         <div id="logo"></div>
      </div>
         <div id="menu">{% show_menu 0 100 100 100 %}</div>
      <div id="content">
         {% block content %}
         {% endblock content %}
         <div style="clear: both"></div>
      </div>
      <div id="footer">
        {% if user.is_authenticated %}
        <span class="login">Logged in as {{ user.username }}  <a href="{% url 'logout' %}">[logout]</a> <a href="{% url 'admin:index' %}">[admin]</a></span>
        {% else %}
        <span class="login"><a href="{% url 'login' %}">[login]</a></span>
        {% endif %}           
      </div>

    </div>

{% render_block "js" %}
</body>
</html>


<div style="width: 940px; margin:0 auto">
    <ul class="nav">

    </ul>
</div>

language_machines/templates/fullwidth.html
{% extends "base.html" %}
{% load cms_tags %}

{% block title %}{% page_attribute 'title' %}{% endblock title %}

{% block content %}
	{% placeholder "content" %}
{% endblock content %}

language_machines/templates/login.html
{% extends "base.html" %}

{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

<form method="post" action="{% url 'django.contrib.auth.views.login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login" />
<input type="hidden" name="next" value="{% url 'admin:index' %}" />
</form>

{% endblock %}

language_machines/templates/person_index_plugin.html
<div class="personindex">
{% for person in persons %}
    <div class="person">
        <h3><a href="{{ person.getslug() }}">{{ person.firstname }} {{ person.lastname }} {% if person.nickname %}{{ person.nickname }}{% endif %}</a> <span class="title">{{ person.title }}</span></h3>
        <span class="function">{{ person.get_function_display() }} {% if person.function2 %}{{ person.get_function2_display() }}{% endif %}</span> <span class="affiliation">{{ person.affiliation }}</span>
        {% if person.email %}
        <span class="item"><a href="mailto:{{ person.email }}">{{ person.email }}</a></span>
        {% endif %}
        <p>{{ person.description }}</p>
    </div>
{% endfor %}
</div>

language_machines/templates/person_plugin_index.html
<div class="personindex">
{% for person in persons %}
    <div class="person">
        <h3><a href="{{ person.getslug() }}">{{ person.firstname }} {{ person.lastname }} {% if person.nickname %}{{ person.nickname }}{% endif %}</a> <span class="title">{{ person.title }}</span></h3>
        <span class="function">{{ person.get_function_display() }} {% if person.function2 %}{{ person.get_function2_display() }}{% endif %}</span> <span class="affiliation">{{ person.affiliation }}</span>
        {% if person.email %}
        <span class="item"><a href="mailto:{{ person.email }}">{{ person.email }}</a></span>
        {% endif %}
        <p>{{ person.description }}</p>
    </div>
{% endfor %}
</div>

language_machines/templates/personindex.html
{% extends "base.html" %}
{% load cms_tags menu_tags sekizai_tags staticfiles %}

{% block title %}{% page_attribute 'title' %}{% endblock title %}

{% block content %}
<h1>Team</h1>

{% placeholder "content" %}

<div class="index">
{% for person in persons %}
    {% if not person.left_date %}
        {% include 'personitem.html' %}
    {% endif %}
{% endfor %}
</div>

<h2>Former team members</h2>

<div class="index">
{% for person in persons %}
    {% if person.left_date %}
        {% include 'personitem.html' %}
    {% endif %}
{% endfor %}
</div>

{% endblock content %}

language_machines/templates/personitem.html
{% load cms_tags menu_tags sekizai_tags %}

<div class="item">
        {% if not person.left_date %}
        {% if person.image %}
        <div class="imagespace">
            <img src="{{ person.image.url }}" alt="{{ person }}" title="{{ person }}" width="120" height="160" />
        </div>
        {% else %}
        <div class="imagespace">
            <img src="{{ person.getrandomlama }}" alt="{{ person }}" title="{{ person }}" height="160" />
        </div>
        {% endif %}
        {% endif %}
        <h3><a href="{% url 'person' person.id %}">{{ person.firstname }} {{ person.lastname }} {% if person.nickname %}({{ person.nickname }}){% endif %}</a> <span class="title">{{ person.title }}</span></h3>
        <span class="function">{{ person.get_function_display }} {% if person.function2 %}&amp; {{ person.get_function2_display }}{% endif %}</span>
        <span class="affiliation">{{ person.affiliation }}</span>
        {% if person.email %}
        <span class="field"><a href="mailto:{{ person.email }}">{{ person.email }}</a></span>
        {% endif %}
        <p>{{ person.description }}</p>
        <div style="clear: both"></div>
</div>

language_machines/templates/project_index_plugin.html
<div class="projectindex">
{% for project in projects %}
    <div class="project">
        <h3><a href="{{ project.getslug() }}">{{ project.name }}</a></span></h3>
        <span class="sponsor">{{ project.sponsor }}</span>
        {% if project.website %}
        <span class="item"><a href="{{ project.website }}">{{ project.website }}</a></span>
        {% endif %}
        <p>{{ project.description }}</p>
    </div>
{% endfor %}
</div>

language_machines/templates/sidebar_left.html
{% extends "base.html" %}
{% load cms_tags %}

{% block title %}{% page_attribute 'title' %}{% endblock title %}

{% block content %}
    <div style="width:20%; float:left;">
        {% placeholder "sidebar" %}
    </div>
    <div style="width:80%; float:left;">
        {% placeholder "content" %}
    </div>
{% endblock content %}

language_machines/templates/sidebar_right.html
{% extends "base.html" %}
{% load cms_tags %}

{% block title %}{% page_attribute 'title' %}{% endblock title %}

{% block content %}
    <div style="width:80%; float:left;">
        {% placeholder "content" %}
    </div>
    <div style="width:20%; float:left;">
        {% placeholder "sidebar" %}
    </div>
{% endblock content %}

language_machines/templates/software_index_plugin.html
<div class="sofwareindex">
{% for app in software %}
    <div class="software">
        <h3><a href="{{ app.getslug() }}">{{ app.name }}</a></h3>
        <p>{{ app.description }}</p>
    </div>
{% endfor %}
</div>

language_machines/templates/software_plugin_index.html
<div class="sofwareindex">
{% for app in software %}
    <div class="software">
        <h3><a href="{{ app.getslug() }}">{{ app.name }}</a></h3>
        <p>{{ app.description }}</p>
    </div>
{% endfor %}
</div>

language_machines/templates/software_view_plugin.html
<div class="personview">
        <h1>{{ software.name }}<h1>
        {% if software.website %}
        <span class="item"><label>Website:</label> <a href="{{ software.website }}">{{ software.website }}</a></span>
        {% endif %}
        {% if software.source %}
        <span class="item"><label>Source:</label> <a href="{{ software.source }}">{{ software.source }}</a></span>
        {% endif %}
        {% if software.webservice %}
        <span class="item"><label>Webservice:</label> <a href="{{ software.webservice }}">{{ software.webservice }}</a></span>
        {% endif %}
        {% if software.demo %}
        <span class="item"><label>Demo:</label> <a href="{{ software.demo }}">{{ software.demo }}</a></span>
        {% endif %}
        <p>{{ software.description }}</p>
</div>

language_machines/templates/softwareitem.html
{% load cms_tags menu_tags sekizai_tags staticfiles %}

<div class="item">
    {% if software.image %}
    <div class="imagespacesmall">
        <img src="{{ software.image.url }}" alt="{{ software }}" title="{{ software }}" width="60" height="80" />
    </div>
    {% else %}
    <div class="imagespacesmall">
        <img src="{% static 'lama-logo-soft.png' %}" alt="{{ software }}" title="{{ software }}" width="60" height="80" />
    </div>
    {% endif %}
    <h3><a href="{% url 'softwareview' software.id %}">{{ software.name }}</a></h3>
    {% if software.authors or software.externalauthors %}
    <span class="field">by 
    {% for author in software.authors.all %}
    <a href="{% url 'person' author.id %}">{{ author }}</a> {% if not forloop.last %}, {% endif %}
    {% endfor %}
    {% if software.externalauthors %}
    , {{ software.externalauthors }}
    {% endif %}
    </span>
    {% endif %}
    {% if software.website %}
    <span class="field"><a href="{{ software.website }}">{{ software.website }}</a></span>
    {% elif software.source %}
    <span class="field"><a href="{{ software.source }}">{{ software.source }}</a></span>
    {% endif %}
    <p>{{ software.description }}</p>
</div>